[project]
name = "templaterx"
version = "0.1.0"
description = ""
authors = [
    { name = "Matheus Wagner", email = "matheuswagnerdossantos@outlook.com" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "babel (==2.17.0)",
    "cffi (==1.17.1)",
    "cryptography (==44.0.1)",
    "docxcompose (==1.4.0)",
    "docxtpl (==0.20.1)",
    "greenlet (==3.1.1)",
    "jinja2 (==3.1.6)",
    "lxml (==5.3.1)",
    "markupsafe (==3.0.3)",
    "oracledb (==2.5.1)",
    "psycopg2-binary (==2.9.11)",
    "pycparser (==2.22)",
    "python-docx (==1.2.0)",
    "python-dotenv (==1.0.1)",
    "sqlalchemy (==2.0.38)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "typing-extensions (==4.12.2)",
    "six (==1.17.0)",
    "setuptools (>=80.9.0,<81.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "faker (>=39.0.0,<40.0.0)",
]
